[profile.default]
src = 'src'
out = 'out'
test = 'src/test'
script = 'src/script'
cache_path  = 'cache_forge'
libs = ['node_modules', 'lib']


solc_version = "0.8.24"
evm_version = 'cancun'
extra_output_files = ["metadata"]
optimizer = true
optimizer-runs = 200

[rpc_endpoints]
mainnet = "${RPC_MAINNET}" 

# See more config options https://github.com/foundry-rs/foundry/tree/master/config